const Listing = require('./models/Listing');

const seedListings = [
  { title: '6 Aana view plot facing Shivapuri', type: 'land', district: 'Kathmandu', city: 'Budhanilkantha, Kathmandu', price: 18500000, areaSqft: 2731, desc: 'Flat, road-facing plot with south exposure and full mountain views. Blacktop road access, electricity and water line already at the boundary. Clean lalpurja, no bank loan pending.', tags: ['Road access', 'Clean title', 'Mountain view'], sellerName: 'Kamal Shrestha', sellerPhone: '98510XXXXX', featured: true },
  { title: '3BHK modern home in Bharatpur-10', type: 'house', district: 'Chitwan', city: 'Bharatpur, Chitwan', price: 24500000, areaSqft: 1850, beds: 3, baths: 3, year: 2021, desc: 'Newly built RCC house with attached parking, solar backup and a small garden. Ten minutes from Bharatpur Airport, close to schools and the hospital.', tags: ['Solar backup', 'Parking', 'Near airport'], sellerName: 'Sunita Gurung', sellerPhone: '98460XXXXX', featured: true },
  { title: '2 Bigha farmland near East-West Highway', type: 'land', district: 'Rupandehi', city: 'Butwal, Rupandehi', price: 32000000, areaSqft: 145800, desc: 'Fertile, currently cultivated farmland with direct highway frontage — strong potential for commercial re-zoning. Irrigation canal runs along the northern edge.', tags: ['Highway frontage', 'Irrigated', 'Zoning potential'], sellerName: 'Devi Prasad Oli', sellerPhone: '98570XXXXX' },
  { title: 'Lakeview 2BHK apartment, Lakeside', type: 'apartment', district: 'Kaski', city: 'Pokhara, Kaski', price: 16800000, areaSqft: 1120, beds: 2, baths: 2, year: 2019, desc: 'Fully furnished apartment on the 4th floor with a partial lake view balcony. Walking distance to Phewa Lake, cafes and the tourist strip.', tags: ['Furnished', 'Lake view', 'Elevator'], sellerName: 'Nabin Thapa', sellerPhone: '98060XXXXX', featured: true },
  { title: 'Corner shop-house on Mahendra Marg', type: 'commercial', district: 'Sunsari', city: 'Itahari, Sunsari', price: 29500000, areaSqft: 2400, desc: 'Three-storey commercial building on a corner plot, currently rented to two tenants generating steady monthly income. High foot traffic location.', tags: ['Rental income', 'Corner plot', 'High footfall'], sellerName: 'Rajesh Yadav', sellerPhone: '98420XXXXX' },
  { title: '8 Aana plot near Ring Road, Koteshwor', type: 'land', district: 'Kathmandu', city: 'Koteshwor, Kathmandu', price: 52000000, areaSqft: 3642, desc: 'Prime urban plot 400m from Ring Road with existing boundary wall. Suitable for an apartment building or commercial complex.', tags: ['Boundary wall', 'Urban', 'Investment grade'], sellerName: 'Anita Maharjan', sellerPhone: '98010XXXXX' },
  { title: 'Traditional 4BHK house, Bhaktapur', type: 'house', district: 'Bhaktapur', city: 'Bhaktapur', price: 19800000, areaSqft: 2100, beds: 4, baths: 2, year: 2015, desc: 'Brick-and-timber home in Newari architectural style close to Bhaktapur Durbar Square. Quiet lane, good for a guesthouse conversion.', tags: ['Heritage style', 'Guesthouse potential'], sellerName: 'Suresh Maharjan', sellerPhone: '98530XXXXX' },
  { title: '1 Bigha 5 Kattha farmland, Nepalgunj outskirts', type: 'land', district: 'Banke', city: 'Nepalgunj, Banke', price: 14200000, areaSqft: 91125, desc: 'Open agricultural land with tube-well irrigation already installed. Ten minutes from the Indian border checkpoint, popular for cross-border trade access.', tags: ['Tube-well', 'Border access'], sellerName: 'Firoz Ansari', sellerPhone: '98150XXXXX' },
  { title: 'Studio apartment near Jhamsikhel', type: 'apartment', district: 'Lalitpur', city: 'Lalitpur', price: 9800000, areaSqft: 620, beds: 1, baths: 1, year: 2022, desc: "Compact modern studio ideal for a young professional or rental investment. Located in the heart of Jhamsikhel's cafe district.", tags: ['Rental ready', 'Cafe district'], sellerName: 'Prakriti Bajracharya', sellerPhone: '98110XXXXX' },
  { title: 'Roadside commercial land, Biratnagar', type: 'land', district: 'Morang', city: 'Biratnagar, Morang', price: 38500000, areaSqft: 5000, desc: 'Vacant commercial plot on the main road into Biratnagar, previously used as a fuel depot site. All utility lines already connected.', tags: ['Utilities ready', 'Main road'], sellerName: 'Bimal Rai', sellerPhone: '98220XXXXX' },
  { title: 'Hillside 5BHK bungalow, Dhulikhel', type: 'house', district: 'Kavre', city: 'Dhulikhel, Kavre', price: 31000000, areaSqft: 3200, beds: 5, baths: 4, year: 2018, desc: 'Spacious bungalow with a private garden and sunrise-facing terrace overlooking the valley. Popular weekend-home area with cool climate year-round.', tags: ['Garden', 'Sunrise view', 'Weekend home'], sellerName: 'Milan Karki', sellerPhone: '98410XXXXX', featured: true },
  { title: '2 Kattha residential plot, Janakpur', type: 'land', district: 'Dhanusha', city: 'Janakpur, Dhanusha', price: 6200000, areaSqft: 7290, desc: 'Small residential plot in a developing neighborhood close to Janaki Mandir. Good starter investment with rising nearby land value.', tags: ['Developing area', 'Starter plot'], sellerName: 'Ramesh Jha', sellerPhone: '98330XXXXX' },
  { title: '3BHK apartment with parking, New Baneshwor', type: 'apartment', district: 'Kathmandu', city: 'Kathmandu', price: 21500000, areaSqft: 1450, beds: 3, baths: 2, year: 2020, desc: 'Centrally located apartment close to the UN Park and major office districts. Includes one covered parking space and 24-hour security.', tags: ['24hr security', 'Covered parking'], sellerName: 'Sabina Lama', sellerPhone: '98040XXXXX' },
  { title: 'Warehouse plot near Dharan industrial belt', type: 'commercial', district: 'Sunsari', city: 'Dharan, Sunsari', price: 27000000, areaSqft: 8712, desc: 'Large flat plot suited for a warehouse or small factory, adjacent to the existing industrial belt with heavy-vehicle road access.', tags: ['Industrial zone', 'Heavy vehicle access'], sellerName: 'Ganesh Limbu', sellerPhone: '98620XXXXX' }
];

async function seedIfEmpty() {
  const count = await Listing.countDocuments();
  if (count > 0) {
    console.log(`Listings already seeded (${count} in DB) — skipping.`);
    return;
  }
  await Listing.insertMany(seedListings);
  console.log(`Seeded ${seedListings.length} sample listings.`);
}

module.exports = { seedIfEmpty };
